language: perl
perl:
   - "5.16"
   - "5.14"
   - "5.12"
   - "5.10"

install:
   # Deal with all of the DZIL dependancies, quickly and quietly
   - cpanm --quiet --notest --skip-satisfied Dist::Zilla
   - dzil authordeps | grep -vP '[^\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest --skip-satisfied

   # Install the lowest possible required version for the dependencies
   - export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1
   - export OLD_CPANM_OPT=$PERL_CPANM_OPT
   - export PERL_CPANM_OPT='--mirror http://cpan.metacpan.org/ --mirror http://search.cpan.org/CPAN '$PERL_CPANM_OPT
   - cpanm --verbose DAVECROSS/WWW-Shorten-2.06.tar.gz
   - cpanm --verbose CORION/parent-0.215.tar.gz
   - cpanm --verbose JPEACOCK/version-0.7701.tar.gz
   - cpanm --verbose DAGOLDEN/Module-Build-0.3601.tar.gz
   - cpanm --verbose DAGOLDEN/Module-Build-0.3601.tar.gz
   - cpanm --verbose MSCHWERN/Test-Simple-0.94.tar.gz
   - export PERL_CPANM_OPT=$OLD_CPANM_OPT
script:
   - dzil smoke --release --author
